import Footer from 'app/components/organisms/footer'
import Head from 'next/head'
import Header from 'app/components/organisms/header'
import HomeSection from 'app/components/organisms/home'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Project X</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
      <Header/>
      <main>
        <HomeSection />
      </main>

      <Footer />
    </div>
  )
}
